name: Hangload
description: "Hangload -- The new way to load your bike"
exclude: [README.md, package.json, index.js, Rakefile, node_modules, src, backups]
permalink: pretty
repository: hangload/static
phone: +49 177 5067837
lead: simply more <br class="xs-hide"> <span class="bold">freedom</span>
email: info@hangload.com
address:
  - Forster Stra√üe 3
  - 10999 Berlin
  - Germany
